[package]
name = "rs-compressor"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.100"
js-sys = "0.3.77"
web-sys = { version = "0.3.77", features = ["console"] }

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
