name: Build and Deploy Docker Images to GHCR

on:
  push:
    branches:
      - master  # Trigger this workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push js-compressor image
      - name: Build and Push js-compressor image
        working-directory: ./js-compressor
        run: |
          docker build -t ghcr.io/${{ github.repository }}/js-compressor:latest .
          docker push ghcr.io/${{ github.repository }}/js-compressor:latest

      # Build and push rs-compressor image
      - name: Build and Push rs-compressor image
        working-directory: ./rs-compressor
        run: |
          docker build -t ghcr.io/${{ github.repository }}/rs-compressor:latest .
          docker push ghcr.io/${{ github.repository }}/rs-compressor:latest
